quarkus:
  rest-client:
    gitlab-api:
      url: ${GITLAB_URL}
    ollama-api:
      url: ${OLLAMA_API_URL}
      connect-timeout: ${OLLAMA_CONNECT_TIMEOUT}
      read-timeout: ${OLLAMA_READ_TIMEOUT}

gitlab:
  auth:
    token: ${GITLAB_TOKEN}

ollama:
  prompt-path: ${OLLAMA_PROMPT_PATH}
  model: ${OLLAMA_MODEL}
  temperature: ${OLLAMA_TEMPERATURE}

pmd:
  path: ${PMD_PATH}
  ruleset: ${PMD_RULESET}
  suppressions: ${PMD_SUPPRESSIONS}